### ISSUE TITLE
Função "entrada" 

### ISSUE THREAD

**Issue by eptaccio** [enredo/enredo#3]
Criar uma função para input de dados.

ex:
```javascript
variavel valor = entrada("informe um valor")
```

**Comment by Pedro-Souza** [comment]
Como seria o código gerado no build? com o [prompt](https://www.npmjs.com/package/prompt)?

**Comment by eptaccio** [comment]
Poderia, mas acho que a forma como o build é executo teria que mudar, porque hoje eu executo o file e printo o `stdout`

https://github.com/enredo/enredo/blob/a378f72a11f86e5b57a89b071aed32bf898900f7/index.js#L52-L55

**Comment by eptaccio** [comment]
@Pedro-Souza e eu não queria alterar isso, porque dessa forma seria bem fácil construir o [editor](https://github.com/enredo/editor) (simulando uma IDE)

**Comment by Pedro-Souza** [comment]
Hmm, verdade @eptaccio, tinha me esquecido que apenas printa o stdout. Pensa em alguma outra forma de se fazer isso sem alterar a forma que o build é executado?

**Comment by eptaccio** [comment]
@Pedro-Souza  Cara, acho que que o esquema vai ser alterar o a execução do build mesmo.

Deixar o [modulo principal](https://github.com/enredo/enredo/blob/master/index.js) resposável só por gerar o build, os modulos que forem utilizar ele (cli e editor) implementam como quiser a execucação. 

No caso do [cli](https://github.com/enredo/enredo/blob/master/cli.js) seria alterado nessas linhas, em vez de apenas printar o resultado, ele executaria o file.

https://github.com/enredo/enredo/blob/a378f72a11f86e5b57a89b071aed32bf898900f7/cli.js#L7-L12

Acho que tirando essa responsabilidade do módulo principal vai ficar mais fácil reutilizar futuramente c:

**Comment by eptaccio** [comment]
Nesse esquema dária para parametrizar como essa função 'entrada' seria gerada, o cli poderia usar esse modulo que você citou ali em cima, e o editor a gente ve futuramente como fazer

**Comment by eptaccio** [comment]
@Pedro-Souza já dá para começar a pensar em como fazer usando o módulo [prompt ](https://www.npmjs.com/package/prompt) ou algo similar 😀
